let add = function foo(x, y) {
    return x + y;
}
console.log(add(2, 5)); // 7
console.log(foo(2, 5)); // ReferenceError

